from processes.local.minesite import MineSite
from processes.local.roomplanner import RoomPlanner
from processes.local.upgradesite import UpgradeSite
from processes.local.feedsite import FeedSite
from processes.local.buildsite import BuildSite
from processes.local.spawning import Spawning
from processes.local.repairsite import RepairSite
from processes.local.defence import Defence
from processes.local.logistics import Logistics
from processes.local.management import Management
from processes.local.mineralsite import MineralSite
from processes.local.wallrepair import WallRepair
